string plan_id
autolabor_coverage/HybridTransitionRequest[] transitions
autolabor_coverage/TransitProfile transit_profile
float64 total_timeout_sec
---
bool success
autolabor_coverage/HybridTransitionResult[] results
string message
---
uint32 candidate_index
uint32 transition_index
uint8 search_stage
string stage_name
float64 elapsed_sec
