string client_request_id
autolabor_coverage/CoverageRegion[] regions
float32 operation_width_m
float32 overlap_ratio
bool allow_reverse_transit
float64 max_speed_mps
float64 reverse_speed_mps
float64 max_angular_speed_rps
float64 linear_accel_mps2
float64 angular_accel_rps2
float64 direction_change_penalty_sec
float64 segment_handoff_penalty_sec
float64 transit_replan_period_sec
string map_digest
---
bool accepted
string message
string batch_id
