string plan_id
float64 max_speed_mps
bool allow_reverse_transit
float64 reverse_speed_mps
float64 max_angular_speed_rps
float64 linear_accel_mps2
float64 angular_accel_rps2
float64 direction_change_penalty_sec
float64 segment_handoff_penalty_sec
float64 transit_replan_period_sec
---
bool accepted
string message
